apiVersion: v1
kind: Service
metadata:
  name: devops-demo-service
  namespace: devops-demo
  labels:
    app: devops-demo
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3000"
spec:
  type: LoadBalancer
  selector:
    app: devops-demo
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
  sessionAffinity: ClientIP
